logging:
  level:
    org.springframework: ERROR
    com.devarch: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

spring:
  jpa:
    defer-datasource-initialization: true
  cloud:
    function:
      definition: bookingSupplier;bookingConsumer
    stream:
      kafka:
      bindings:
        bookingSupplier-out-0:
          destination: booking-created
        bookingConsumer-in-0:
          destination: booking-updated

#----------Alternate Configuration below------------------

#spring.cloud.stream:
#
#  function:
#    definition: bookingSupplier;bookingConsumer
#  bindings:
#    bookingSupplier-out-0:
#      destination: booking-created
#    bookingConsumer-in-0:
#      destination: booking-updated
