spring.cloud.stream:
  function:
    definition: bookingProcessor
  bindings:
    bookingProcessor-in-0:
      destination: booking-created

server:
  port: 8081

service:
  endpoints:
    payment: http://localhost:8082
    seat-reservation: http://localhost:8083
