logging:
  level:
    org.springframework: ERROR
    com.devarch: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"


spring.cloud.stream:
  function:
    definition: bookingProcessor
  bindings:
    bookingProcessor-in-0:
      destination: booking-created
    bookingProcessor-out-0:
      destination: booking-updated
  kafka:
    binder:
      replication-factor: 1

server:
  port: 8081

service:
  endpoints:
    payment: http://localhost:8082
    seat-reservation: http://localhost:8083
